language: csharp
solution: Verse.sln

matrix:
  include:
    - os: linux
      dist: xenial
      dotnet: 2.1.502

script:
  - dotnet restore Verse.sln
  - dotnet build ./Verse/Verse.csproj -c Release -f netstandard2.0
  - dotnet build ./Verse.Test/Verse.Test.csproj -c Release -f netcoreapp2.0
  - dotnet test ./Verse.Test/Verse.Test.csproj -c Release -f netcoreapp2.0
